### ISSUE TITLE
copy to clipboard "lightning run notebook my_notebook" is coppying "lightning run notebook my_notebook"

### ISSUE THREAD

**Issue by edenlightning** [Lightning-AI/lightning-hpo#123]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/66261195/190017974-ab41d86d-d5d3-4f15-a0c7-f02155581dd5.png">

**Comment by tchaton** [comment]
Yes, this is a known limitation of chrome. I think we will simply disable it locally. @ethanwharris
