### ISSUE TITLE
Add ability to install system packages as part of an experiment

### ISSUE THREAD

**Issue by lantiga** [Lightning-AI/lightning-hpo#207]
## 🚀 Feature

We should add the ability to specify package names that will be installed through `apt install` (via `BuildConfig`).

### Motivation

Some users need extra deps on their system in order to run their training.

### Alternatives

An alternative could be support for custom Dockerfile's but it's out of scope for now.

**Comment by Atharva-Phatak** [comment]
@lantiga I can work on this :). If could divulge some details that would nice :). Like what do you have in mind or how do you think the user should specify extra deps ?

**Comment by lantiga** [comment]
Hey @Atharva-Phatak! Sorry we needed to speed it through https://github.com/Lightning-AI/lightning-hpo/pull/210
