### ISSUE TITLE
Run notebook from the CLI

### ISSUE THREAD

**Issue by ethanwharris** [Lightning-AI/lightning-hpo#28]
## 🚀 Feature

Launch a notebook from the CLI:
- Implement the command to add entry to DB
- Implement the controller to launch a notebook work

**Comment by tchaton** [comment]
TODOS:
- [] Release [lightning-notebook](https://github.com/Lightning-AI/LAI-Jupyter-Component) to PYPI
- [] Implement RunNotebookConfig / RunNotebookCommand in lightning_hpo/commands/notebooks/run.py
- [] Implement RunController:
-  with run_notebook_handler to store the received RunNotebookConfig from the RunNotebookCommand in the database

**Comment by tchaton** [comment]
Closed by https://github.com/Lightning-AI/lightning-hpo/pull/69 and https://github.com/Lightning-AI/lightning-hpo/pull/128
