### ISSUE TITLE
Download artefacts from the CLI (Cloud)

### ISSUE THREAD

**Issue by ethanwharris** [Lightning-AI/lightning-hpo#31]
## 🚀 Feature

Command to download an artefact after having listed them

TODOS:

- [] Add a DownloadArtefactCommand in lightning_hpo/commands/artefacts/download.py. Simply use LightningClient and list the artifacts. Use this [reference](https://github.com/Lightning-AI/lightning/blob/1bcb5c301df67c7db60ddd33b040c06d58bedfd5/src/lightning_app/utilities/commands/base.py#L98).

**Comment by tchaton** [comment]
Closed by https://github.com/Lightning-AI/lightning-hpo/pull/66 and https://github.com/Lightning-AI/lightning-hpo/pull/65
